# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title parametric bootstrap regression
#' @export
bootstrap_robust_regression <- function(X, y, times) {
    .Call(`_YetAnotherRStudioApplication_bootstrap_robust_regression`, X, y, times)
}

